import {
  getValidAccessToken,
  json,
  moodTargets,
  readJsonBody,
  spotifyRequest,
} from "../_lib/spotify.js";

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return json(res, 405, { error: "Method not allowed" });
  }

  let mood;
  try {
    const body = await readJsonBody(req);
    mood = String(body.mood || "").toLowerCase();
  } catch {
    return json(res, 400, { error: "Invalid JSON payload" });
  }

  const settings = moodTargets[mood];
  if (!settings) {
    return json(res, 400, { error: "Unsupported mood" });
  }

  const accessToken = await getValidAccessToken(req, res);
  if (!accessToken) {
    return json(res, 401, { error: "Not authenticated with Spotify" });
  }

  try {
    const me = await spotifyRequest("GET", "/me", accessToken);
    let recs = await spotifyRequest("GET", "/recommendations", accessToken, {
      query: {
        ...settings,
        limit: 20,
        market: me.country || "US",
      },
    });

    let uris = (recs.tracks || []).map((track) => track.uri).filter(Boolean);
    if (!uris.length) {
      // Fallback: relax audio targets and use only genre seeds.
      recs = await spotifyRequest("GET", "/recommendations", accessToken, {
        query: {
          seed_genres: settings.seed_genres,
          limit: 20,
          market: me.country || "US",
        },
      });
      uris = (recs.tracks || []).map((track) => track.uri).filter(Boolean);
    }

    if (!uris.length) {
      return json(res, 404, {
        error: "No recommended tracks for this mood",
        details: "Try a different mood or reconnect Spotify.",
      });
    }

    const now = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });

    const playlist = await spotifyRequest("POST", `/users/${me.id}/playlists`, accessToken, {
      body: {
        name: `${mood[0].toUpperCase() + mood.slice(1)} Mood Mix (${now})`,
        description: `Auto-generated by Moodify for a ${mood} vibe`,
        public: false,
      },
    });

    await spotifyRequest("POST", `/playlists/${playlist.id}/tracks`, accessToken, {
      body: { uris },
    });

    return json(res, 200, {
      ok: true,
      playlist: {
        id: playlist.id,
        name: playlist.name,
        url: playlist.external_urls?.spotify,
      },
      tracksAdded: uris.length,
    });
  } catch (error) {
    const statusCode = Number(error?.status) || 500;
    const details =
      error?.details?.error?.message || error?.details?.error || error?.details || error?.message;

    return json(res, statusCode, {
      error: "Failed to create playlist",
      details,
    });
  }
}
